from __future__ import annotations

import asyncio
import logging
from typing import Any

from homeassistant.components import frontend
from homeassistant.components.lovelace.dashboard import LovelaceStorage
from homeassistant.components.lovelace.const import (
    ConfigNotFound,
    CONF_TITLE,
    LOVELACE_DATA,
    MODE_STORAGE,
)
from homeassistant.config_entries import ConfigEntry
from homeassistant.const import CONF_ICON
from homeassistant.core import HomeAssistant

from .const import DOMAIN

_LOGGER = logging.getLogger(__name__)

_DASHBOARD_LOCK = "dashboard_lock"

DASHBOARD_URL_PATH = "amperepoint-panel"
DASHBOARD_STORAGE_ID = "amperepoint_panel"
DASHBOARD_TITLE = "AmperePoint"
DASHBOARD_ICON = "mdi:ev-station"


def _dashboard_config() -> dict[str, Any]:
    # The card resolves entities from the entity registry and offers a device
    # selector, so one shared panel serves every configured charger.
    return {
        "title": DASHBOARD_TITLE,
        "views": [
            {
                "title": DASHBOARD_TITLE,
                "path": "charger",
                "icon": DASHBOARD_ICON,
                "panel": True,
                "cards": [{"type": "custom:amperepoint-q22-card"}],
            }
        ],
    }


async def _async_remove_legacy_dashboard(hass: HomeAssistant, entry: ConfigEntry) -> None:
    """Remove the old per-entry dashboard generated by earlier versions."""
    url_path = f"amperepoint-{entry.entry_id[:8]}"
    dashboards = hass.data[LOVELACE_DATA].dashboards
    legacy = dashboards.get(url_path)
    if not isinstance(legacy, LovelaceStorage):
        return
    try:
        frontend.async_remove_panel(hass, url_path)
    except (KeyError, ValueError):  # pragma: no cover - defensive
        pass
    dashboards.pop(url_path, None)
    try:
        await legacy.async_delete()
    except Exception:  # pragma: no cover - defensive
        _LOGGER.debug("Could not delete legacy dashboard storage %s", url_path)
    _LOGGER.info("Removed legacy AmperePoint dashboard at /%s", url_path)


async def async_create_dashboard(hass: HomeAssistant, entry: ConfigEntry) -> str:
    """Ensure the single shared AmperePoint panel exists."""
    domain_data = hass.data.setdefault(DOMAIN, {})
    lock = domain_data.setdefault(_DASHBOARD_LOCK, asyncio.Lock())

    async with lock:
        await _async_remove_legacy_dashboard(hass, entry)

        existing = hass.data[LOVELACE_DATA].dashboards.get(DASHBOARD_URL_PATH)
        if existing is not None:
            return DASHBOARD_URL_PATH

        item = {
            "id": DASHBOARD_STORAGE_ID,
            CONF_ICON: DASHBOARD_ICON,
            CONF_TITLE: DASHBOARD_TITLE,
            "url_path": DASHBOARD_URL_PATH,
        }
        storage = LovelaceStorage(hass, item)
        hass.data[LOVELACE_DATA].dashboards[DASHBOARD_URL_PATH] = storage
        frontend.async_register_built_in_panel(
            hass,
            "lovelace",
            frontend_url_path=DASHBOARD_URL_PATH,
            require_admin=False,
            show_in_sidebar=True,
            sidebar_title=DASHBOARD_TITLE,
            sidebar_icon=DASHBOARD_ICON,
            config={"mode": MODE_STORAGE},
        )
        try:
            await storage.async_load(False)
        except ConfigNotFound:
            await storage.async_save(_dashboard_config())
            _LOGGER.info("Created AmperePoint dashboard at /%s", DASHBOARD_URL_PATH)
        return DASHBOARD_URL_PATH
